repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: no-commit-to-branch
    -   id: check-yaml
    -   id: check-merge-conflict
    -   id: end-of-file-fixer
        exclude: ^(energy_scraper/energy_scraper/settings.py|energy_scraper/energy_scraper/middlewares.py)
    -   id: trailing-whitespace
-   repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: ["--profile", "black", "--filter-files"]
-   repo: https://github.com/python/black
    rev: 23.7.0
    hooks:
    - id: black
      exclude: ^web_app/migrations/
-   repo: https://github.com/pycqa/flake8.git
    rev: 6.1.0
    hooks:
    - id: flake8
      exclude: ^(smart_energy/settings.py|energy_scraper/energy_scraper/settings.py|energy_scraper/energy_scraper/middlewares.py|energy_scraper/energy_scraper/pipelines.py)
