version: "3.9"
services:
  api:
    build: .
    ports:
      - "8000:8000"
    command: ./run_server.sh
    env_file:
      - .env
    volumes:
      - .:/code
    depends_on:
      - db
      - splash
      - redis

  splash:
    image: scrapinghub/splash:3.5
    ports:
      - "8050:8050"

  db:
    image: postgres:16
    restart: always
    env_file:
      - .env
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 3s
      retries: 10

  redis:
    image: redis:7.0.0
    restart: always
    ports:
      - "6380:6380"
    command:
      redis-server --port 6380 --save 20 1 --loglevel warning
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD-SHELL", "redis-cli -p 6380 ping | grep PONG"]
      interval: 1s
      timeout: 3s
      retries: 5


volumes:
  postgres_data:
  redis_data:
