# Generated by Django 5.0 on 2024-01-03 15:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="energyprice",
            name="date",
            field=models.DateField(),
        ),
    ]
