# Generated by Django 5.0 on 2024-01-08 08:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_alter_energyprice_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="energyprice",
            name="hour",
            field=models.IntegerField(
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(24),
                ]
            ),
        ),
    ]
