# Generated by Django 5.0 on 2024-02-03 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumeenergydevice',
            name='plan_period',
            field=models.CharField(max_length=120),
        ),
    ]
