# Generated by Django 5.0 on 2024-02-03 13:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_alter_consumeenergydevice_plan_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumeenergydevice',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='consumeenergydevice',
            name='energy_consumption',
            field=models.FloatField(default=2, validators=[django.core.validators.MinValueValidator(0)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='consumeenergydevice',
            name='energy_unit',
            field=models.CharField(default=2, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produceenergydevice',
            name='capacity_unit',
            field=models.CharField(default=2, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produceenergydevice',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='storeenergydevice',
            name='capacity_unit',
            field=models.CharField(default='elo', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='storeenergydevice',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='storeenergydevice',
            name='capacity',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
