# Generated by Django 5.0 on 2024-02-23 16:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0003_consumeenergydevice_enabled_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produceenergydevice',
            name='capacity',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='storeenergydevice',
            name='capacity',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
